package api

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	pmdb "aipmc/db"
	"aipmc/web"
)

type agentSession struct {
	Agent     string `json:"agent"`
	StartedAt int64  `json:"started_at"`
}

func (s *Server) ensureSessionGC() {
	s.sessionsInit.Do(func() {
		go func() {
			for {
				time.Sleep(60 * time.Second)
				s.sessionsMu.Lock()
				cutoff := time.Now().Add(-24 * time.Hour).Unix()
				filtered := s.sessions[:0]
				for _, sess := range s.sessions {
					if sess.StartedAt >= cutoff {
						filtered = append(filtered, sess)
					}
				}
				s.sessions = filtered
				s.sessionsMu.Unlock()
			}
		}()
	})
}

// handleAgentLaunch starts an AI coding agent in a native terminal window.
// POST /pmai/agent/launch  {"agent": "claude"|"codex"|"gemini"}
func (s *Server) handleAgentLaunch(w http.ResponseWriter, body map[string]any) {
	agentName, _ := body["agent"].(string)
	if agentName == "" {
		web.SendError(w, 400, "缺少 'agent' 字段 (claude/codex/gemini)")
		return
	}
	agentName = strings.ToLower(agentName)

	gcfg := pmdb.LoadGlobalConfig()
	proxyPort := gcfg.ProxyPort
	proxyURL := fmt.Sprintf("http://127.0.0.1:%d", proxyPort)
	upstreamKey := os.Getenv("UPSTREAM_KEY")

	log.Printf("[AGENT LAUNCH] ========== 启动请求 ==========")
	log.Printf("[AGENT LAUNCH] agent=%s proxy_port=%d proxy_url=%s",
		agentName, proxyPort, proxyURL)
	log.Printf("[AGENT LAUNCH] config: upstream=%s anthropic=%s model=%s",
		gcfg.UpstreamURL, gcfg.AnthropicURL, gcfg.ProxyModel)
	log.Printf("[AGENT LAUNCH] upstream_key: %s", maskKey(upstreamKey))

	var cmd *exec.Cmd
	var envOverrides []string
	switch agentName {
	case "claude", "claude-code":
		cmd = exec.Command("claude")
		envOverrides = []string{
			"ANTHROPIC_BASE_URL=" + proxyURL,
			"ANTHROPIC_AUTH_TOKEN=" + upstreamKey,
		}
		if gcfg.ProxyModel != "" {
			envOverrides = append(envOverrides, "ANTHROPIC_MODEL="+gcfg.ProxyModel)
		}
	case "codex", "openai-codex":
		// Codex CLI uses TOML config files, not env vars, for API base URL.
		// The profile ~/.codex/proxy.config.toml is generated by aipmc setup.
		// We regenerate it on every launch to ensure the proxy port is current.
		if err := codexWriteProxyProfile(proxyURL, gcfg.ProxyModel); err != nil {
			log.Printf("[AGENT LAUNCH] ERROR: 写入 Codex profile 失败: %v", err)
			web.SendError(w, 500, fmt.Sprintf("Codex 配置失败: %v", err))
			return
		}
		// Codex reads API key from env; -p proxy selects the proxy profile
		// Use interactive TUI (not 'exec' — that requires a prompt argument)
		cmd = exec.Command("codex", "-p", "proxy")
		envOverrides = []string{
			"OPENAI_API_KEY=" + upstreamKey,
		}
	case "gemini", "gemini-cli":
		cmd = exec.Command("gemini")
		envOverrides = []string{
			"GEMINI_API_KEY=" + upstreamKey,
			"GOOGLE_API_KEY=" + upstreamKey,
			"GEMINI_API_BASE=" + proxyURL,
			"GOOGLE_API_BASE=" + proxyURL,
			"GOOGLE_GEMINI_BASE_URL=" + proxyURL,
		}
	default:
		log.Printf("[AGENT LAUNCH] ERROR: 未知 agent=%s", agentName)
		web.SendError(w, 400, fmt.Sprintf("未知 agent: %s (支持 claude/codex/gemini)", agentName))
		return
	}

	// Build clean environment: essential system vars + agent-specific overrides.
	// We do NOT inherit all os.Environ() to prevent cross-agent pollution
	// (e.g. ANTHROPIC_* vars confusing Codex/Gemini).
	essential := essentialSystemEnv()
	cmd.Env = append(essential, envOverrides...)

	// Set working directory so agents find project files and .pmai hooks
	cmd.Dir, _ = os.Getwd()

	log.Printf("[AGENT LAUNCH] cmd=%s args=%v", cmd.Path, cmd.Args)
	log.Printf("[AGENT LAUNCH] dir=%s", cmd.Dir)
	log.Printf("[AGENT LAUNCH] essential_env=%d overrides=%d total=%d",
		len(essential), len(envOverrides), len(cmd.Env))
	for _, e := range envOverrides {
		log.Printf("[AGENT LAUNCH] env: %s", maskKey(e))
	}

	log.Printf("[AGENT LAUNCH] 正在打开终端...")
	if err := launchInTerminal(cmd, envOverrides); err != nil {
		log.Printf("[AGENT LAUNCH] ERROR: 终端启动失败: %v", err)
		web.SendError(w, 500, fmt.Sprintf("启动失败: %v", err))
		return
	}
	log.Printf("[AGENT LAUNCH] ========== 启动完成 ==========")

	s.ensureSessionGC()
	s.sessionsMu.Lock()
	s.sessions = append(s.sessions, agentSession{
		Agent:     agentName,
		StartedAt: time.Now().Unix(),
	})
	s.sessionsMu.Unlock()

	web.SendJSON(w, map[string]any{"ok": true, "agent": agentName})
}

func (s *Server) handleAgentSessions(w http.ResponseWriter) {
	s.ensureSessionGC()
	s.sessionsMu.Lock()
	list := make([]agentSession, len(s.sessions))
	copy(list, s.sessions)
	s.sessionsMu.Unlock()
	if list == nil {
		list = []agentSession{}
	}
	web.SendJSON(w, map[string]any{"sessions": list})
}

// codexWriteProxyProfile writes ~/.codex/proxy.config.toml with the current proxy settings.
// This matches the format generated by setupCodexMCP in setup.go. Codex reads this profile
// when launched with `codex -p proxy`.
func codexWriteProxyProfile(proxyURL, proxyModel string) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	codexDir := filepath.Join(homeDir, ".codex")
	os.MkdirAll(codexDir, 0755)

	modelName := proxyModel
	if modelName == "" {
		modelName = "gpt-5.1"
	}

	profile := fmt.Sprintf(`# Codex proxy profile — auto-generated by AIPM Agent Launcher
# Usage: codex -p proxy exec "prompt"
model = "%s"
model_provider = "custom"
model_reasoning_effort = "medium"

[model_providers.custom]
name = "AIPM Proxy"
base_url = "%s/v1"
env_key_instructions = "not needed for local proxy"
`, modelName, proxyURL)

	profilePath := filepath.Join(codexDir, "proxy.config.toml")
	if err := os.WriteFile(profilePath, []byte(profile), 0644); err != nil {
		return err
	}
	log.Printf("[AGENT CODEX] profile written to %s:\n%s", profilePath, profile)
	return nil
}

func maskKey(s string) string {
	if idx := strings.Index(s, "="); idx >= 0 && idx < len(s)-1 {
		val := s[idx+1:]
		if len(val) > 8 {
			return s[:idx+1] + val[:4] + "..." + val[len(val)-4:]
		}
		return s[:idx+1] + "***"
	}
	return s
}

// essentialSystemEnv returns a minimal set of system environment variables
// that agents need to function (PATH, home dirs, temp dirs, etc).
func essentialSystemEnv() []string {
	keep := map[string]bool{
		"PATH": true, "PATHEXT": true,
		"HOME": true, "USERPROFILE": true,
		"APPDATA": true, "LOCALAPPDATA": true,
		"TEMP": true, "TMP": true,
		"SYSTEMROOT": true, "SYSTEMDRIVE": true,
		"HOMEDRIVE": true, "HOMEPATH": true,
		"ComSpec": true, "USERNAME": true, "COMPUTERNAME": true,
		"ProgramFiles": true, "ProgramFiles(x86)": true,
		"ProgramData": true, "ALLUSERSPROFILE": true,
		// Keep these so the agent doesn't try to connect elsewhere
	}
	var out []string
	for _, e := range os.Environ() {
		key := e
		if idx := strings.Index(e, "="); idx >= 0 {
			key = e[:idx]
		}
		if keep[key] {
			out = append(out, e)
		}
	}
	return out
}

func launchInTerminal(cmd *exec.Cmd, envOverrides []string) error {
	log.Printf("[AGENT TERM] platform=%s exe=%s args=%v dir=%s overrides=%d",
		runtime.GOOS, cmd.Path, cmd.Args, cmd.Dir, len(envOverrides))

	switch runtime.GOOS {
	case "windows":
		exePath, err := exec.LookPath(cmd.Args[0])
		if err != nil {
			log.Printf("[AGENT TERM] ERROR: LookPath 失败: %v", err)
			return fmt.Errorf("未找到 %s，请确认已安装并在 PATH 中", cmd.Args[0])
		}
		log.Printf("[AGENT TERM] resolved exe=%s", exePath)

		workDir := cmd.Dir
		if workDir == "" {
			workDir, _ = os.Getwd()
		}

		var sb strings.Builder
		sb.WriteString("@echo off\r\n")
		sb.WriteString("chcp 65001 >nul 2>&1\r\n")
		fmt.Fprintf(&sb, "cd /d \"%s\"\r\n", workDir)
		sb.WriteString("title AIPM Agent - " + cmd.Args[0] + "\r\n")

		// Write ONLY the agent-specific env overrides.
		// System env vars are inherited by the cmd process, NOT explicitly set.
		// This prevents cross-agent pollution (e.g. ANTHROPIC_* vars leaking to Codex).
		for _, e := range envOverrides {
			sb.WriteString("set " + e + "\r\n")
		}

		fmt.Fprintf(&sb, "echo Starting AIPM Agent - %s\r\n", cmd.Args[0])
		sb.WriteString("echo.\r\n")
		sb.WriteString(`"` + exePath + `"`)
		for i := 1; i < len(cmd.Args); i++ {
			sb.WriteString(" " + cmd.Args[i])
		}
		sb.WriteString("\r\n")
		sb.WriteString("if %ERRORLEVEL% NEQ 0 (\r\n")
		sb.WriteString("  echo.\r\n")
		fmt.Fprintf(&sb, "  echo Error: %s exited with code %%ERRORLEVEL%%\r\n", cmd.Args[0])
		sb.WriteString("  echo Make sure the command is installed and configured correctly.\r\n")
		sb.WriteString(")\r\n")
		sb.WriteString("pause\r\n")
		sb.WriteString("del \"%~f0\"\r\n")

		tmpFile, _ := os.CreateTemp("", "aipmc-launch-*.bat")
		tmpPath := tmpFile.Name()
		tmpFile.WriteString(sb.String())
		tmpFile.Close()

		log.Printf("[AGENT BAT] ====== BAT 脚本 (%s) ======\n%s[AGENT BAT] ====== 脚本结束 ======", tmpPath, sb.String())

		termCmd := exec.Command("cmd", "/c", "start",
			fmt.Sprintf("AIPM Agent - %s", cmd.Args[0]), "cmd", "/c", tmpPath)
		log.Printf("[AGENT TERM] 执行: cmd /c start \"AIPM Agent - %s\" cmd /c %s", cmd.Args[0], tmpPath)
		return termCmd.Start()
	case "darwin":
		cdDir := cmd.Dir
		if cdDir == "" {
			cdDir, _ = os.Getwd()
		}
		// Export only agent-specific env vars
		var exports string
		for _, e := range envOverrides {
			exports += "export " + e + "; "
		}
		script := fmt.Sprintf(`tell app "Terminal" to do script "cd '%s' && %s %s"`,
			cdDir, exports, strings.Join(cmd.Args, " "))
		log.Printf("[AGENT TERM] osascript: %s", script)
		return exec.Command("osascript", "-e", script).Start()
	default:
		// Export env overrides before starting the command
		var exports string
		for _, e := range envOverrides {
			exports += "export " + e + "; "
		}
		fullCmd := exports + strings.Join(cmd.Args, " ")
		terms := []string{"x-terminal-emulator", "gnome-terminal", "konsole", "xfce4-terminal"}
		for _, term := range terms {
			if _, err := exec.LookPath(term); err == nil {
				log.Printf("[AGENT TERM] using terminal: %s cmd=%s", term, fullCmd)
				return exec.Command(term, "-e", fullCmd).Start()
			}
		}
		log.Printf("[AGENT TERM] fallback: direct start cmd=%s args=%v dir=%s", cmd.Path, cmd.Args, cmd.Dir)
		return cmd.Start()
	}
}
