package api

import (
	"os"
	"strings"
	"testing"
)

// TestMergeCodexProxyProfile_Empty writes the full template including the
// mcp_servers.aipm root table so codex never sees a tools-only orphan table.
func TestMergeCodexProxyProfile_Empty(t *testing.T) {
	got := mergeCodexProxyProfile("", "gpt-5.1", "medium", "http://127.0.0.1:19530")
	for _, want := range []string{
		`model = "gpt-5.1"`,
		`base_url = "http://127.0.0.1:19530/v1"`,
		"[mcp_servers.aipm]",
		`command = "aipmc"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("fresh profile missing %q:\n%s", want, got)
		}
	}
}

// TestMergeCodexProxyProfile_PreservesCodexState reproduces the reported bug:
// a profile with codex-managed hooks.state + a tools sub-table must keep both,
// get its model fields refreshed, and gain the missing root table so codex
// stops rejecting the profile with "invalid transport in mcp_servers.aipm".
func TestMergeCodexProxyProfile_PreservesCodexState(t *testing.T) {
	existing := `# Codex proxy profile — auto-generated by AIPM Agent Launcher
model = "deepseek-v4-flash"
model_provider = "custom"
model_reasoning_effort = "medium"

[model_providers.custom]
name = "AIPM Proxy"
base_url = "http://127.0.0.1:19530/v1"
env_key_instructions = "not needed for local proxy"

[hooks.state]

[hooks.state."/Users/dazsec/workspace/aipmc/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:abc"

[mcp_servers.aipm.tools.aipm_list_commits]
approval_mode = "approve"

[tui.model_availability_nux]
"gpt-5.5" = 4
`
	got := mergeCodexProxyProfile(existing, "gpt-5.6-sol", "high", "http://127.0.0.1:19531")

	// model fields refreshed
	for _, want := range []string{
		`model = "gpt-5.6-sol"`,
		`model_reasoning_effort = "high"`,
		`base_url = "http://127.0.0.1:19531/v1"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("merge result missing %q:\n%s", want, got)
		}
	}
	// codex-managed state preserved
	for _, want := range []string{
		`[hooks.state."/Users/dazsec/workspace/aipmc/.codex/hooks.json:post_tool_use:0:0"]`,
		`trusted_hash = "sha256:abc"`,
		`[mcp_servers.aipm.tools.aipm_list_commits]`,
		`approval_mode = "approve"`,
		`[tui.model_availability_nux]`,
		`"gpt-5.5" = 4`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("merge result dropped codex state %q:\n%s", want, got)
		}
	}
	// root table inserted before the tools sub-table
	if !strings.Contains(got, "[mcp_servers.aipm]\ncommand = \"aipmc\"") {
		t.Errorf("merge result missing mcp_servers.aipm root table:\n%s", got)
	}
	idxRoot := strings.Index(got, "[mcp_servers.aipm]\n")
	idxTools := strings.Index(got, "[mcp_servers.aipm.tools")
	if idxRoot < 0 || idxTools < 0 || idxRoot > idxTools {
		t.Errorf("root table (idx=%d) must precede tools sub-table (idx=%d):\n%s", idxRoot, idxTools, got)
	}
	// idempotent: merging again must not change anything
	again := mergeCodexProxyProfile(got, "gpt-5.6-sol", "high", "http://127.0.0.1:19531")
	if again != got {
		t.Errorf("merge not idempotent:\n--- before ---\n%s\n--- after ---\n%s", got, again)
	}
}

// TestMergeCodexProxyProfile_MissingTopLevelFields inserts model fields before
// the first table so they don't land inside [hooks.state].
func TestMergeCodexProxyProfile_MissingTopLevelFields(t *testing.T) {
	existing := `[hooks.state]

[hooks.state."/x"]
trusted_hash = "sha256:abc"
`
	got := mergeCodexProxyProfile(existing, "gpt-5.1", "medium", "http://127.0.0.1:19530")
	if !strings.Contains(got, "model = \"gpt-5.1\"\nmodel_provider = \"custom\"\nmodel_reasoning_effort = \"medium\"\n[hooks.state]") {
		t.Errorf("top-level fields must be inserted before [hooks.state]:\n%s", got)
	}
}

// TestWriteCodexProxyProfile_EndToEnd verifies the exported writer refreshes a
// broken profile (tools sub-table without root) and keeps codex trust records.
func TestWriteCodexProxyProfile_EndToEnd(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	codexDir := home + "/.codex"
	if err := os.MkdirAll(codexDir, 0755); err != nil {
		t.Fatal(err)
	}
	broken := `model = "deepseek-v4-flash"

[hooks.state."/Users/dazsec/workspace/aipmc/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:abc"

[mcp_servers.aipm.tools.aipm_list_commits]
approval_mode = "approve"
`
	profilePath := codexDir + "/proxy.config.toml"
	if err := os.WriteFile(profilePath, []byte(broken), 0644); err != nil {
		t.Fatal(err)
	}

	if err := WriteCodexProxyProfile("http://127.0.0.1:19530", "gpt-5.6-sol", "high"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(profilePath)
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)
	for _, want := range []string{
		`model = "gpt-5.6-sol"`,
		`trusted_hash = "sha256:abc"`,
		"[mcp_servers.aipm]\ncommand = \"aipmc\"",
		`[mcp_servers.aipm.tools.aipm_list_commits]`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("repaired profile missing %q:\n%s", want, got)
		}
	}
}
